defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: 9cGvv2Yzjm

development:
  database: favpal_development
  <<: *defaults

test:
  database: favpal_test 
  <<: *defaults

production:
  database: favpal_production
  <<: *defaults
